name: Python package

on: 
  schedule:
    - cron: '*/5 * * * *'

jobs:
  publish:
    name: AutoScrape
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install packages
        run: pip install -r requirements/pub.txt
      - name: Run scraper
        run: python source.py
